# Generated by Django 5.0.6 on 2024-09-02 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parent_panel", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="history",
            options={"verbose_name": "History", "verbose_name_plural": "History"},
        ),
        migrations.AlterModelOptions(
            name="permission",
            options={
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
            },
        ),
        migrations.AlterModelOptions(
            name="permitteduser",
            options={
                "verbose_name": "PermittedUser",
                "verbose_name_plural": "PermittedUsers",
            },
        ),
        migrations.AlterModelOptions(
            name="userchildren",
            options={
                "verbose_name": "User-Child",
                "verbose_name_plural": "Users-Children",
            },
        ),
    ]
