# Generated by Django 5.0.6 on 2024-12-18 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parent_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-date'], 'verbose_name': 'History', 'verbose_name_plural': 'History'},
        ),
    ]
