# Generated by Django 5.0.6 on 2024-09-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "parent_panel",
            "0002_alter_history_options_alter_permission_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="qr_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="permission",
            name="state",
            field=models.CharField(
                choices=[
                    ("SLEEP", "Sleep"),
                    ("NOTIFY", "Notify"),
                    ("ACTIVE", "Active"),
                    ("CLOSED", "Closed"),
                ],
                default="SLEEP",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="two_factor_code",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
