# Generated by Django 5.0.6 on 2024-09-02 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teacher_panel", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="children",
            options={"verbose_name": "Child", "verbose_name_plural": "Children"},
        ),
        migrations.AlterModelOptions(
            name="classroom",
            options={"verbose_name": "Classroom", "verbose_name_plural": "Classrooms"},
        ),
        migrations.AlterModelOptions(
            name="userclassroom",
            options={
                "verbose_name": "User-Classroom",
                "verbose_name_plural": "Users-Classrooms",
            },
        ),
    ]
