# Generated by Django 5.0.6 on 2024-10-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backbone", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="temp_password",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
