env:
  NAME: Test

name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set environment variables
      run: |
        echo "DEBUG=${{ secrets.DEBUG }}" >> $GITHUB_ENV
        echo "USE_AZURE_POSTGRES=${{ secrets.USE_AZURE_POSTGRES }}" >> $GITHUB_ENV
        echo "ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}" >> $GITHUB_ENV
        echo "CSRF_TRUSTED_ORIGINS=${{ secrets.CSRF_TRUSTED_ORIGINS }}" >> $GITHUB_ENV
        echo "SECURE_SSL_REDIRECT=${{ secrets.SECURE_SSL_REDIRECT }}" >> $GITHUB_ENV

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        python manage.py test
      env:
        DEBUG: ${{ secrets.DEBUG }}
        USE_AZURE_POSTGRES: ${{ secrets.USE_AZURE_POSTGRES }}
        ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
        CSRF_TRUSTED_ORIGINS: ${{ secrets.CSRF_TRUSTED_ORIGINS }}
        SECURE_SSL_REDIRECT: ${{ secrets.SECURE_SSL_REDIRECT }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
