name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DEBUG: 1
  USE_AZURE_POSTGRES: 0
  SECRET_KEY: "8vcoox1shj#p#@kx0s*t@sp#^-ij09z)rn++e&zoj_6l+@&f2%"
  ALLOWED_HOSTS: "localhost 127.0.0.1 [::1]"
  CSRF_TRUSTED_ORIGINS: "https://localhost https://127.0.0.1"
  SECURE_SSL_REDIRECT: 0

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test parent_panel.tests
